version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: myapp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d

  spring-app:
    image: ye0314/macos:v2
    container_name: myapp-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dbname
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  db_data:
