spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/dbname?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: password
logging:
  level:
    org.springframework.jdbc.core: DEBUG

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs
    groups:
      enabled: false
    resolve-schema-properties: true
  default-consumes-media-type: application/json
  auto-tag-classes: true
  swagger-ui:
    operations-sorter: method
    path: /swagger-ui.html
  show-actuator: false
